### ISSUE TITLE
Composer dependencies fail

### ISSUE THREAD

**Issue by kodekraft** [basho/riak-phppb-client#13]
When attempting to add this package, the following error occurs:

```
[vagrant@gtp gtp]$ composer require basho/riak-pb
Using version ^1.1 for basho/riak-pb
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for basho/riak-pb ^1.1 -> satisfiable by basho/riak-pb[v1.1.0].
    - basho/riak-pb v1.1.0 requires allegro/protobuf dev-master -> no matching package found.
```

**Comment by christophermancini** [comment]
Yea, I know the composer install is a little complicated at the moment due to our fork of https://github.com/allegro/php-protobuf.
- We forked the project and submitted changes but the project went stale
- When the project came back, the maintainer chose not to merge our changes
- We have not released any versions of the fork with our changes, resulting in composer require of `dev-master`

So, there are a few ways around this. You can set the minimum-stability of your project to dev but this will force all of your dependencies to dev releases which is not ideal. The other solution is to add something like the following to your composer.json:

``` json
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/basho/php-protobuf"
    }
  ],
```

Then add the following to the require section of your composer.json.

``` json
    "allegro/protobuf": "dev-master"
```

We will try to get this resolved in the very near future. Let me know if you need further help.

**Comment by kodekraft** [comment]
Thanks for the update Chris!  I went ahead with your latter solution, since I already had to alias the package since I needed to use the php7 branch for the extension.
